project:
  type: website

website:
  title: "Statistical Graphics and Visualization 36-315 Spring 25"
  sidebar:
    background: primary
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ryurko/statds-36315-spring25
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: demos.qmd
        text: Demos

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true

execute:
  freeze: auto
