---
title: "Demos"
---

| Demo   | Date    | Title              | Demo file                            |
|--------|---------|--------------------|--------------------------------------|
| 1      | Jan 13  | Into the tidyverse | [HTML](demos/01-into-tidyverse.qmd)  |
| 2      | Feb 17  | Scatterplots and Linear Regression | [HTML](demos/02-plot-2dquant.qmd)  |
| 3      | Feb 19  | More Regression with Penguins | [HTML](demos/03-regression.qmd)  |
| 4      | Mar 10  | Nonlinear Regression and Pairs Plots | [HTML](demos/04-nonlinear-pairs.qmd)  |
| 5      | Mar 12  | Contour Plots, Heat Maps, and Into High-Dimensional Data | [HTML](demos/05-heatmap-highdim.qmd)  |
| 6      | Mar 17  | Visualizing Distances for High-Dimensional Data | [HTML](demos/06-mds.qmd)  |
| 7      | Mar 19  | More MDS and Creating Dendrograms | [HTML](demos/07-clustering.qmd)  |
| 8      | Mar 24  | Principal Component Analysis | [HTML](demos/08-pca.qmd)  |
| 9      | Mar 26  | Visualizing Trends | [HTML](demos/09-trends.qmd)  |
| 10     | Mar 31  | Visualizing time series data | [HTML](demos/10-time-series.qmd)  |
| 11     | Apr 2  | Animations, modifying colors and themes | [HTML](demos/11-anim-colors-themes.qmd)  |

