---
title: "Lectures"
---

| Lecture   | Date    | Title                                | Materials                              |
|-----------|---------|--------------------------------------|----------------------------------------|
| 1         | Jan 13  | Introduction and Grammar of Graphics | [slides](lectures/01-intro.qmd)        |
| 2         | Jan 15  | 1D Categorical Data                  | [slides](lectures/02-1dcat.qmd)        |
| 3         | Jan 22  | Statistical Inference for 1D Categorical Data  | [slides](lectures/03-1dcat-infer.qmd)        |
| 4         | Jan 27  | Power and Multiple Testing  | [slides](lectures/04-power-multiple-testing.qmd)        |
| 5         | Jan 29  | Visualizations and Inference for 2D Categorical Data  | [slides](lectures/05-2dcat.qmd)        |
| 6         | Feb 3  | Visualizing 1D Quantitative Data  | [slides](lectures/06-1dquant.qmd)        |
| 7         | Feb 5  | Density Estimation  | [slides](lectures/07-density-estimation.qmd)        |
| 8         | Feb 10  | Graphical Inference for 1D Quantitative Data  | [slides](lectures/08-1dquant-inference.qmd)        |
| 9         | Feb 12  | Comparing Distributions and Statistical Power  | [slides](lectures/09-compare-distr-power.qmd)        |
| 10        | Feb 17  | Scatterplots and Linear Regression  | [slides](lectures/10-2dquant.qmd)        |
| 11        | Feb 19  | Inference with Linear Regression  | [slides](lectures/11-regression-inference.qmd)        |
| 12        | Feb 24  | Midsemester Review | [slides](lectures/12-midsemester-review.qmd)        |
| 13        | Mar 10  | Nonlinear Regression and Pairs Plots | [slides](lectures/13-nonlinear-pairs.qmd)        |
| 14        | Mar 12  | Contour Plots, Heat Maps, and Into High-Dimensional Data | [slides](lectures/14-contours-heatmaps.qmd)        |


