{
  "hash": "9cf08e53b5b9665bdf656d42cb2e9a41",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo 03: More Regression with Penguins\"\nformat: html\n---\n\n\n\n\n## Regression with Penguins\n\n**The graphs below don't have proper titles, axis labels, legends, etc.  Please take care to do this on your own graphs.** Throughout this demo we will use the [`palmerpenguins` dataset](https://allisonhorst.github.io/palmerpenguins/articles/intro.html). To access the data, you will need to install the `palmerpenguins` package:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"palmerpenguins\")\n```\n:::\n\n\n\n\nWe load the penguins data in the same way as before:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(palmerpenguins)\ndata(penguins)\nhead(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n  <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n1 Adelie  Torgersen           39.1          18.7               181        3750\n2 Adelie  Torgersen           39.5          17.4               186        3800\n3 Adelie  Torgersen           40.3          18                 195        3250\n4 Adelie  Torgersen           NA            NA                  NA          NA\n5 Adelie  Torgersen           36.7          19.3               193        3450\n6 Adelie  Torgersen           39.3          20.6               190        3650\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n\n\n\n## Simple Linear Regression (based only on bill length)\n\nFirst, we can run a simple linear regression (the first model) based only on bill length. We can display this line via `geom_smooth()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = bill_length_mm, y = bill_depth_mm)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = TRUE)\n```\n\n::: {.cell-output-display}\n![](03-regression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nAnd display the regression model output using `summary()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(bill_depth_mm ~ bill_length_mm, data = penguins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_depth_mm ~ bill_length_mm, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.1381 -1.4263  0.0164  1.3841  4.5255 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    20.88547    0.84388  24.749  < 2e-16 ***\nbill_length_mm -0.08502    0.01907  -4.459 1.12e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.922 on 340 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.05525,\tAdjusted R-squared:  0.05247 \nF-statistic: 19.88 on 1 and 340 DF,  p-value: 1.12e-05\n```\n\n\n:::\n:::\n\n\n\n\nWe can write this regression model as:\n\n$$\\text{depth} \\sim N(\\beta_0 + \\beta_L \\cdot \\text{length}, \\sigma^2)$$\n\nNote that $\\beta_0$ is the **intercept** and $\\beta_L$ is the **slope**.\n\nThus, our estimates are:\n\n+ $\\hat{\\beta}_0 = 20.88547$\n+ $\\hat{\\beta}_L = 12.43$\n+ $\\hat{\\sigma}^2 = 1.922^2$\n\n## Multiple Linear Regression (Additive)\n\nWe can also run the second model, which is based on length and species, but with only additive effects. First, we'll check the counts of the species variable to ensure that the species with the highest number of observations if the reference level (i.e., the first level for a factor variable):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(penguins$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Adelie Chinstrap    Gentoo \n      152        68       124 \n```\n\n\n:::\n:::\n\n\n\n\nLooks like we're lucky and that the `Adelie` species is the most popular and is already first due to alphabetical order. _What function would we need to do to re-order the variable?_\n\nNext, we'll fit the regression that accounts for `species` without an interaction - so it's just an additive effect:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndepth_lm_species_add <- lm(bill_depth_mm ~ bill_length_mm + species,\n                           data = penguins)\nsummary(depth_lm_species_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_depth_mm ~ bill_length_mm + species, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.4529 -0.6864 -0.0508  0.5519  3.5915 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      10.59218    0.68302  15.508  < 2e-16 ***\nbill_length_mm    0.19989    0.01749  11.427  < 2e-16 ***\nspeciesChinstrap -1.93319    0.22416  -8.624 2.55e-16 ***\nspeciesGentoo    -5.10602    0.19142 -26.674  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9533 on 338 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.769,\tAdjusted R-squared:  0.7669 \nF-statistic: 375.1 on 3 and 338 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThis tells us that `Chinstrap` is different from `Adelie` and `Gentoo` is different from `Adelie`, but it does NOT tell us `Chinstrap` is different from `Gentoo`. That would require another model with a __reordered__ `species` variable. _Exercise: Reorder `species` so that `Gentoo` is the reference level and compare to the results above_.\n\nWe can manually extract intercepts and coefficients to use for plotting (__read the code comments!__):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate species-specific intercepts in order:\nintercepts <- # First for `Adelie` it's just the initial intercept\n  c(coef(depth_lm_species_add)[\"(Intercept)\"],\n    # Next for `Chinstrap` it's the intercept plus the `Chinstrap` term:\n    coef(depth_lm_species_add)[\"(Intercept)\"] + \n      coef(depth_lm_species_add)[\"speciesChinstrap\"],\n    # And finally for `Gentoo` it's again the intercept plus the `Gentoo` term\n    coef(depth_lm_species_add)[\"(Intercept)\"] + \n      coef(depth_lm_species_add)[\"speciesGentoo\"])\n\n# Create a small table to store the intercept, slopes, and species:\nlines_tbl <- tibble(\"intercepts\" = intercepts,\n                    # Slopes are the same for each, thus use rep()\n                    \"slopes\" = rep(coef(depth_lm_species_add)[\"bill_length_mm\"],\n                                   3),\n                    # And the levels of species:\n                    \"species\" = levels(penguins$species))\n```\n:::\n\n\n\n\n\nWe can now plot this model by specifying the regression lines with `geom_abline()` using the newly constructed `lines_tbl` as the data for this layer:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = bill_length_mm, y = bill_depth_mm)) +\n  geom_point(alpha = 0.5) +\n  geom_abline(data = lines_tbl,\n              aes(intercept = intercepts, slope = slopes,\n                  color = species)) +\n  labs(x = \"Bill length (mm)\", y = \"Bill depth (mm)\", \n       title = \"Bill depth versus weight by species\")\n```\n\n::: {.cell-output-display}\n![](03-regression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nThis is a great example of [__Simpson's Paradox__](https://en.wikipedia.org/wiki/Simpson%27s_paradox)! We originally observed a negative linear relationship between depth and length, but now observe a positive linear relationship within species!\n\n## Multiple Linear Regression (Interactive)\n\nNext, we can run the third model, which is based on length and species, including interaction effects. This is the default type of model displayed when we map `species` to the color aesthetic for the `geom_smooth()` layer. In the plot below, we display across both layers, `geom_point()` and `geom_smooth()` by mapping `species` to color in the initial `ggplot` canvas construction:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = TRUE) +\n  labs(x = \"Bill length (mm)\", y = \"Bill depth (mm)\", \n       title = \"Bill depth versus weight by species\")\n```\n\n::: {.cell-output-display}\n![](03-regression_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nWhat about the summary of this model? Is the inclusion of interaction terms relevant? Note that by default, multiplying two variables in the `lm()` formula below includes __both__ the additive __AND__ interaction terms.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndepth_lm_species_int <- lm(bill_depth_mm ~ bill_length_mm * species,\n                           data = penguins)\nsummary(depth_lm_species_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_depth_mm ~ bill_length_mm * species, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.6574 -0.6675 -0.0524  0.5383  3.5032 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     11.40912    1.13812  10.025  < 2e-16 ***\nbill_length_mm                   0.17883    0.02927   6.110 2.76e-09 ***\nspeciesChinstrap                -3.83998    2.05398  -1.870 0.062419 .  \nspeciesGentoo                   -6.15812    1.75451  -3.510 0.000509 ***\nbill_length_mm:speciesChinstrap  0.04338    0.04558   0.952 0.341895    \nbill_length_mm:speciesGentoo     0.02601    0.04054   0.642 0.521590    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9548 on 336 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.7697,\tAdjusted R-squared:  0.7662 \nF-statistic: 224.5 on 5 and 336 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe interaction terms do NOT appear to be necessary to include. This is justified by both the lack of significance and the slight drop in adjusted R-squared.\n\n## What about the intercept?\n\nRemember the meaning of the intercept term... that is not reasonable in this setting because penguins will never have bills with length of 0mm! We should update the additive model (since we found the interaction terms to not be meaningful) to remove the intercept. This can be done by adding a `0` term to the `lm()` formula:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndepth_lm_remove_b0 <- lm(bill_depth_mm ~ 0 + bill_length_mm + species,\n                         data = penguins)\nsummary(depth_lm_remove_b0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_depth_mm ~ 0 + bill_length_mm + species, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.4529 -0.6864 -0.0508  0.5519  3.5915 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \nbill_length_mm    0.19989    0.01749  11.427  < 2e-16 ***\nspeciesAdelie    10.59218    0.68302  15.508  < 2e-16 ***\nspeciesChinstrap  8.65899    0.86207  10.044  < 2e-16 ***\nspeciesGentoo     5.48616    0.83547   6.567 1.94e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9533 on 338 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.997,\tAdjusted R-squared:  0.997 \nF-statistic: 2.795e+04 on 4 and 338 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n__What changed in the summary output? Why did that occur?__ \n\nWe can copy-and-paste our code from above to add these appropriate regression lines:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate species-specific intercepts in order:\nnew_intercepts <- # First for `Adelie` \n  c(coef(depth_lm_remove_b0)[\"speciesAdelie\"],\n    # Next for `Chinstrap` \n    coef(depth_lm_remove_b0)[\"speciesChinstrap\"],\n    # And finally for `Gentoo` \n    coef(depth_lm_remove_b0)[\"speciesGentoo\"])\n\n# Create a small table to store the intercept, slopes, and species:\nnew_lines_tbl <- \n  tibble(\"intercepts\" = new_intercepts,\n         # Slopes are the same for each, thus use rep()\n         \"slopes\" = rep(coef(depth_lm_remove_b0)[\"bill_length_mm\"],\n                        3),\n         # And the levels of species:\n         \"species\" = levels(penguins$species))\n```\n:::\n\n\n\n\n\nAgain, create the display:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +\n  geom_point(alpha = 0.5) +\n  geom_abline(data = new_lines_tbl,\n              aes(intercept = intercepts, slope = slopes,\n                  color = species)) +\n  labs(x = \"Bill length (mm)\", y = \"Bill depth (mm)\", \n       title = \"Bill depth versus weight by species\")\n```\n\n::: {.cell-output-display}\n![](03-regression_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\nWhy is this the same display as before? [Here's a great description](https://stats.stackexchange.com/questions/26176/removal-of-statistically-significant-intercept-term-increases-r2-in-linear-mo/26205#26205) of why we observe a higher R-squared with the intercept-term excluded from the model.\n\n\n",
    "supporting": [
      "03-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}